builds:
  - binary: acme-dns-client
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags: |
      -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -extldflags '-static'
    goos:
      - linux
      - windows
      - freebsd
      - openbsd
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64

archives:
  - id: tgz
    format: tar.gz
    replacements:
        darwin: macOS
    format_overrides:
        - goos: windows
          format: zip

dockers:
  - image_templates:
    - "joohoi/acme-dns-client:amd64-latest"
    - "joohoi/acme-dns-client:amd64-v{{ .Version }}"
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--build-arg=PLATFORM=amd64"
    extra_files:
      - docker-entrypoint.sh
      - renew
  - image_templates:
    - "joohoi/acme-dns-client:arm32v6-latest"
    - "joohoi/acme-dns-client:arm32v6-v{{ .Version }}"
    goos: linux
    goarch: arm
    goarm: 6
    build_flag_templates:
      - "--build-arg=PLATFORM=arm32v6"
    extra_files:
      - docker-entrypoint.sh
      - renew
  - image_templates:
    - "joohoi/acme-dns-client:arm64v8-latest"
    - "joohoi/acme-dns-client:arm64v8-v{{ .Version }}"
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--build-arg=PLATFORM=arm64v8"
    extra_files:
      - docker-entrypoint.sh
      - renew

docker_manifests:
  - name_template: joohoi/acme-dns-client:latest
    image_templates:
    - joohoi/acme-dns-client:amd64-v{{ .Version }}
    - joohoi/acme-dns-client:arm32v6-v{{ .Version }}
    - joohoi/acme-dns-client:arm64v8-v{{ .Version }}
  - name_template: joohoi/acme-dns-client:v{{ .Version }}
    image_templates:
    - joohoi/acme-dns-client:amd64-v{{ .Version }}
    - joohoi/acme-dns-client:arm32v6-v{{ .Version }}
    - joohoi/acme-dns-client:arm64v8-v{{ .Version }}
